version: '3'

services:

  klusApi:
    build: .
    container_name: klusApi
    image: node:20.9.0-alpine3.17
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://klusApi_db:27017/healthai
    volumes:
      - ./:/usr/klusApi

  klusApi_db:
    container_name: klusApi_db
    image: mongo:4.4.25-focal
    ports:
      - 27017:27017
    depends_on:
      - klusApi
    volumes:
      - ./db/:/usr/data/db
      
  

  