version: '3'

services:

  klusdb:
    container_name: klusdb
    image: mongo:4.4.25-focal
    ports:
      - 27017:27017
    volumes:
      - ./db/:/usr/data/db

  klusapi:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: klusapi
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://klusdb:27017/healthai
      - PORT=5000
    ports:
      - 5000:5000
    depends_on:
      - klusdb
    restart: always
    volumes:
      - ./:/usr/appvol
    